### ISSUE TITLE
Summit Sponsors

### ISSUE THREAD

**Issue by DeaMariaLeon** [pydata/df-summit-23#1]
Should NumFOCUS be included in the sponsors' list? 
@datapythonista

**Comment by datapythonista** [comment]
Fine with me

**Comment by DeaMariaLeon** [comment]
It was just a question in case it was necessary to add it. 
If it's not needed (as in "it doesn't matter") I'll close this. We have stuff to do. :)

**Comment by datapythonista** [comment]
I think it'd be nice to add NumFOCUS. I was checking the companies that paid the expenses of attendees when building that list, and forgot about them, but they are providing support for the event at different levels, so surely worth adding. I'll add the logo when I have time.
